server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG

jwt:
  signerKey: "5fOoIajDcW1ND6jNe1iW6TbPCmWy9jge7KO+OzLhmpNcUvngDfwOZXx6lGq3ZKTq "
  valid-duration: 3600 #second
  refreshable-duration: 120 #seconds
