server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: "jdbc:mysql://:3306/identity_service"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true


    hibernate:
      ddl-auto: update

    show-sql: true

jwt:
  signerKey: "5fOoIajDcW1ND6jNe1iW6TbPCmWy9jge7KO+OzLhmpNcUvngDfwOZXx6lGq3ZKTq "
  valid-duration: 20 #second
  refreshable-duration: 120 #seconds